### ISSUE TITLE
Google Maps API key expired?

### ISSUE THREAD

**Issue by hmacread** [hmacread/keelscape#5]
Google Maps API integration resulting in "are you the developer?" message.

**Comment by hmacread** [comment]
@dbcohen had a thought about this.  I remember thinking at the time that I needed to do something so that I didn't leave the API key in public viewable code here:

        keelscape/configdata.py

Obviously it makes the API key subject to abuse....

**Comment by hmacread** [comment]
@dbcohen another clue.. just found they've moved Google Maps API keys into the console.  Not sure if this is the one it's using:

https://console.cloud.google.com/google/maps-apis/apis/maps-backend.googleapis.com/credentials?authuser=1&project=secret-bay-570&duration=P30D

**Comment by dbcohen** [comment]
I noticed the key there. Given it is only allowed to run from the keelscape namespace I don't think it is open to abuse and given anyone can watch the network calls to see the key it would be in the public. Still reading up on how to use the v3 api

**Comment by dbcohen** [comment]
This is fixed in Version 0-6
