### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by dbcohen** [hmacread/keelscape#7]
The keelscape website says the project is Open Sourced, but there's no license associated with the project. Should this be licensed under MIT, Apache, GPL, etc? Whatever it will be the license needs to be included in the package.

**Comment by hmacread** [comment]
Good point. No one has ever cared until now. Do you have an opinion on how the source code should be liscenced (if at all?)?

**Comment by hmacread** [comment]
@dbcohen I've added Apache 2.0 licensing to to all existing files in a license branch.  If you're happy I'll with Apache 2.0 going forward I'll deploy this code (probably best better figure out how to do that again).

**Comment by hmacread** [comment]
P.s. feel free to hit the merge button on the pull request once you've had a look at the changes.  I'm using Atom as a text editor and I think it removed some pointless whitespace in the html, I can't see that it'll introduce any issues.
